# Generated by Django 5.1.3 on 2024-12-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_access_admin', 'Can access admin site')]},
        ),
    ]
